import json
from pathlib import Path
p=Path(__file__).parent
m={r['frame']:r for r in json.loads((p/'motion_metrics.json').read_text())}
seams=[361,722,1083,1444,1805,2166,2527,2888,3240]
notes={361:'Subtle foreground size contraction and per-channel color change; streetlight/background position mismatch. First new generation frame then nearly held frame.',722:'Car and standing character slightly contract/reposition upward; sky and costume shift color. Background motion does not share the same foreground warp.',1083:'Small contraction plus nonuniform redraw of car and skateboarder; slight grade and line/texture change; first new frame held.',1444:'Foreground contracts/repositions while relative car/skateboarder alignment changes; small cool channel shift.',1805:'City street wide shot: contraction breaks the preceding strong camera scale change. Geometry match is relatively coherent, color change mild.',2166:'Aerial city: global darkening and small crop/geometry reset interrupts pullout/tilt; new clip begins with much slower motion.',2527:'Apartment: whole-frame lightening, shelf/furniture/background proportions change slightly, main subjects redraw; starts with multiple held frames.',2888:'Daylight flight: strong darkening/color shift and local skyline/building/character composition reset. Only 47% of tracked features support one global similarity, so one affine crop cannot reconcile it.',3240:'Library steps: strong geometric redraw and contraction despite preceding forward zoom, plus darker grade. Door/columns/lions require different local corrections. Starts with multiple held frames.'}
results=[]
for f in seams:
 r=m[f].copy();r['assessment']=notes[f];results.append(r)
(p/'confirmed_seams.json').write_text(json.dumps({'source':'IYTYT.mp4','frame_indexing':'zero-based; frame is first frame of new generated segment','fps':'24000/1001','seams':results},indent=2))
lines=['# Independent diagnostics','', 'The nine segment joins are confirmed by direct neighboring-frame inspection plus a full-frame motion/grade scan. Frame numbers are zero-based and name the first frame of the new segment. The cadence is 361 frames for the first eight clips, then 352 for the ninth clip.','', '| Frame | Time (seconds) | Similarity scale | Median B,G,R shift | Notes |','|---|---:|---:|---|---|']
for f in seams:
 r=m[f];lines.append(f"| {f} | {r['time']:.6f} | {r['scale']:.5f} | {r['warped_color']} | {notes[f]} |")
lines+=['','Scale and channel shifts above are diagnostics, not final correction parameters. They compare adjacent frames, so they include genuine scene motion. Measurements are on 480×270 proxies; shifts are in 8-bit channel values. Color residual is measured after sparse optical-flow similarity alignment. One global transform leaves obvious local redraws.','', 'Very large raw frame differences at 23.8–24.3s, 67–75s, 93.0s, 114.8–116.3s and 124–125s mostly come from fast camera moves and changing scene content. Thresholding raw difference alone is therefore not a reliable seam detector here. The actual seams are much stronger outliers in color residual after registration, and have the segment cadence.','', 'The source frequently holds animation on multiple adjacent frames; do not classify every duplicate as a seam or smooth the entire film indiscriminately. Several actual seams also introduce held startup frames, which can produce a temporal hitch even once appearance matches.','', 'Fresh approach suggestion: use separate low-frequency photometric correction, locally varying correspondence with edge-aware confidence, and temporal residual smoothing across the join. A single global transform cannot repair the changing relationships between foreground and background. A single generated inbetween could help true topology/occlusion failures, but it cannot by itself make the velocity and color neighborhoods continuous.']
(p/'REPORT.md').write_text('\n'.join(lines)+'\n')
print(p/'REPORT.md')
